DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT (
  ID INT,
  SEQUENCE INT,
  CONSTRAINT PK_PRODUCT PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS SIZES;

CREATE TABLE SIZES (
  ID INT,
  PRODUCT_ID INT,
  BACK_SOON BOOLEAN,
  SPECIAL BOOLEAN,
  CONSTRAINT PK_SIZES PRIMARY KEY (ID)
  );

DROP TABLE IF EXISTS STOCK;

CREATE TABLE STOCK (
  SIZE_ID INT,
  QUANTITY INT,
  CONSTRAINT PK_STOCK PRIMARY KEY (SIZE_ID)
  );

