DROP TABLE IF EXISTS PRICES;

CREATE TABLE PRICES (
  PRICE_LIST INT,
  PRODUCT_ID INT,
  BRAND_ID INT,
  CURR VARCHAR,
  START_DATE TIMESTAMP,
  END_DATE TIMESTAMP,
  PRICE FLOAT,
  PRIORITY INT,
  CONSTRAINT PK_Person PRIMARY KEY (PRICE_LIST,PRODUCT_ID)
  );